---
# tasks file for ansible-termite
- name: Make sure .config/termite exists
  file:
    path: "{{ansible_env.HOME}}/.config/termite"
    state: directory

- name: Copy termite config
  template:
    src: config.j2
    dest: "{{ansible_env.HOME}}/.config/termite/config"
